'use client'

import { createContext, useContext, useState } from 'react'

export type LanguageCode = 'en' | 'ru'

export const LANGUAGES: { code: LanguageCode; label: string }[] = [
  { code: 'ru', label: 'Русский' },
  { code: 'en', label: 'English' },
]

const COOKIE_KEY = 'aura-language'

type TranslationKey = keyof typeof translations.ru

type LanguageContextValue = {
  language: LanguageCode
  setLanguage: (code: LanguageCode) => void
  t: (key: TranslationKey) => string
}

const translations = {
  ru: {
    homeTitle: 'Что вы хотите создать?',
    home: 'Главная', projects: 'Проекты', chats: 'Чаты', team: 'Команда', plugins: 'Плагины и навыки', myApi: 'Мои API', freebies: 'Бесплатное', search: 'Поиск', newChat: 'Новый чат', newChatOptions: 'Параметры нового чата', favorites: 'Избранное', recentChats: 'Недавние чаты', free: 'Бесплатно',
    profile: 'Профиль', settings: 'Настройки аккаунта', signOut: 'Выйти', signingOut: 'Выход...', guest: 'Гость', switchAccount: 'Сменить аккаунт', noOtherAccounts: 'Других аккаунтов нет', addAccount: 'Добавить аккаунт', continueAsGuest: 'Продолжить как гость', language: 'Язык', languageHelp: 'Язык интерфейса Aura.',
    promptPlaceholder: 'Попросите Aura что-нибудь создать...', promptLabel: 'Запрос', addContent: 'Добавить содержимое', importGithub: 'Импортировать из GitHub', createFigma: 'Создать из Figma', premium: 'Премиум', uploadComputer: 'Загрузить с компьютера', generateImages: 'Генерировать изображения', toggleImages: 'Включить генерацию изображений', skills: 'Плагины и навыки', webSearch: 'Веб-поиск', codeInterpreter: 'Интерпретатор кода', diagrams: 'Диаграммы', folder: 'Папка', newFolder: 'Новая папка', attachExisting: 'Прикрепить существующую', instructions: 'Инструкции', editInstructions: 'Изменить инструкции', resetDefault: 'Сбросить', mcps: 'MCP', manageMcps: 'Управление MCP', addServer: 'Добавить сервер', autoPermissions: 'Авторазрешения', askEveryTime: 'Всегда спрашивать', allowAll: 'Разрешить всё', project: 'Проект', voiceInput: 'Голосовой ввод', selectModel: 'Выбрать модель', addApiKey: 'Добавить API-ключ', myApiDescription: 'Добавляйте ключи внешних провайдеров — они появятся в списке моделей.', newKey: 'Новый ключ', createKey: 'Создать ключ', noKeysTitle: 'Пока нет ни одного ключа', noKeysHelp: 'Добавьте первый API-ключ, чтобы использовать собственные модели в Aura.', keyNameLabel: 'Название', keyNamePlaceholder: 'Например: OpenAI GPT-4o', keyValueLabel: 'API-ключ', keyValuePlaceholder: 'sk-...', deleteKey: 'Удалить ключ', addedOn: 'Добавлен', searchProjects: 'Поиск проектов...', noProjectsFound: 'Проекты не найдены', newProject: 'Новый проект', draft: 'Черновик', createProjectPlaceholder: 'Название проекта', create: 'Создать', cancel: 'Отмена',
    profileTitle: 'Профиль', profileDescription: 'Настройте, как вы отображаетесь в Aura.', backHome: 'На главную', avatar: 'Аватар', avatarHelp: 'Нажмите на изображение, чтобы загрузить JPG, PNG или WebP.', changeAvatar: 'Изменить аватар', yourAvatar: 'Ваш аватар', chooseImage: 'Выберите файл изображения', processImageError: 'Не удалось обработать изображение', canvasError: 'Canvas не поддерживается', imageLoadError: 'Не удалось загрузить изображение', name: 'Имя', nameHelp: 'Отображаемое имя можно менять в любое время — ваш тег останется прежним.', save: 'Сохранить', saved: 'Сохранено', uniqueTag: 'Уникальный тег', tagPermanent: 'Ваш тег уже изменён и теперь постоянный.', tagFromLogin: 'Создан из вашего логина.', lettersOnly: 'Только буквы, цифры, подчёркивания, точки и дефисы', change: 'Изменить', tagWarning: 'Тег можно изменить только один раз. Выбирайте внимательно.', about: 'О себе', bioHelp: 'Короткое описание о вас, не более 500 символов.', bioPlaceholder: 'Расскажите немного о себе...',
    preferences: 'Предпочтения', preferencesDescription: 'Управляйте настройками аккаунта и рабочего пространства.', account: 'Аккаунт', workspace: 'Рабочее пространство', general: 'Общие', memories: 'Память', integrations: 'Интеграции', billing: 'Оплата', members: 'Участники', usage: 'Использование и активность', apiKeys: 'API-ключи', skillsNav: 'Навыки', pluginsNav: 'Плагины', suggestions: 'Подсказки', suggestionsHelp: 'Получайте полезные подсказки в чате для улучшения проекта.', soundNotifications: 'Звуковые уведомления', soundHelp: 'Aura воспроизведёт звук после ответа, если окно неактивно.', chatPosition: 'Положение чата', chatPositionHelp: 'Выберите сторону экрана, на которой расположен чат.', left: 'Слева', right: 'Справа', customInstructions: 'Пользовательские инструкции', customInstructionsHelp: 'Управляйте правилами и предпочтениями для языковой модели.', instructionsPlaceholder: 'Эти инструкции отправляются Aura во всех чатах и проектах.', interfaceTheme: 'Интерфейс и тема', theme: 'Тема', themeHelp: 'Выберите оформление Aura на устройстве.', systemTheme: 'Системная тема', lightTheme: 'Светлая тема', darkTheme: 'Тёмная тема',
    createAccount: 'Создайте аккаунт', welcomeBack: 'С возвращением', signupSubtitle: 'Зарегистрируйтесь, чтобы начать создавать с Aura', signinSubtitle: 'Войдите, чтобы продолжить работу в Aura', username: 'Логин', emailOrUsername: 'Email или логин', password: 'Пароль', showPassword: 'Показать пароль', hidePassword: 'Скрыть пароль', accountCreated: 'Аккаунт создан', signedIn: 'Вход выполнен', signUp: 'Зарегистрироваться', signIn: 'Войти', or: 'или', haveAccount: 'Уже есть аккаунт?', noAccount: 'Нет аккаунта?', genericError: 'Что-то пошло не так', namePlaceholder: 'Ваше имя', identifierPlaceholder: 'you@example.com или ваш_логин',
    forgotPassword: 'Забыли пароль?', forgotTitle: 'Восстановление пароля', forgotSubtitle: 'Укажите email — мы отправим ссылку для сброса пароля.', sendResetLink: 'Отправить ссылку', resetLinkSent: 'Если такой email зарегистрирован, ссылка для сброса отправлена.', backToSignIn: 'Вернуться ко входу', resetTitle: 'Новый пароль', resetSubtitle: 'Придумайте новый пароль для вашего аккаунта.', newPassword: 'Новый пароль', updatePassword: 'Обновить пароль', passwordUpdated: 'Пароль обновлён', invalidResetToken: 'Ссылка недействительна или устарела. Запросите новую.', verificationNote: 'Мы отправили письмо для подтверждения email.', securityTitle: 'Безопасность', emailVerified: 'Email подтверждён', emailNotVerified: 'Email не подтверждён — проверьте почту или отправьте письмо ещё раз.', resendVerification: 'Отправить письмо', verificationSent: 'Отправлено', changePassword: 'Смена пароля', currentPassword: 'Текущий пароль', dangerZone: 'Опасная зона', deleteAccount: 'Удалить аккаунт', deleteAccountHelp: 'Аккаунт и все данные (чаты, проекты, файлы, ключи, память) будут удалены безвозвратно.', deleteAccountConfirm: 'Да, удалить навсегда',
    send: 'Отправить', stop: 'Остановить', thinking: 'Aura думает...', chatError: 'Не удалось получить ответ. Попробуйте ещё раз.', publish: 'Опубликовать', previewGenerating: 'Aura генерирует превью...', previewEmpty: 'Попросите Aura создать сайт или интерфейс — превью появится здесь.', previewUpdated: 'Превью обновлено', renameChatLabel: 'Переименовать', deleteChatLabel: 'Удалить', noRecentChats: 'Пока нет чатов', openMenu: 'Открыть меню', closeMenu: 'Закрыть меню', chatOptions: 'Действия с чатом',
    blankChat: 'Пустой чат', blankProject: 'Пустой проект', createBlankProject: 'Создать пустой проект', blankProjectHelp: 'Будет создан пустой проект, в котором можно начать работу.', projectNameLabel: 'Название проекта', back: 'Назад', createProjectAction: 'Создать проект', importFromUrl: 'Импорт по ссылке', importAction: 'Импортировать', selectRepository: 'Выберите репозиторий', connectGithub: 'Подключить GitHub', githubComingSoon: 'Подключение GitHub скоро будет доступно', invalidRepoUrl: 'Укажите корректную ссылку на репозиторий GitHub', jumpBackIn: 'Продолжить работу', renameProject: 'Переименовать проект', copyProjectId: 'Копировать ID проекта', viewAllChats: 'Все чаты', deleteProject: 'Удалить проект', projectOptions: 'Действия с проектом', projectIdCopied: 'ID скопирован', addToFavorites: 'В избранное', removeFromFavorites: 'Убрать из избранного', noFavorites: 'Нет избранных чатов', daysAgo: '{n} дн. назад', hoursAgo: '{n} ч. назад', justNow: 'только что',
    keyModelLabel: 'ID модели', keyModelPlaceholder: 'например: gpt-4o-mini', keyBaseUrlLabel: 'Base URL', keyBaseUrlPlaceholder: 'https://api.openai.com/v1', advancedOptional: 'Дополнительно (необязательно)', checkKey: 'Проверить', checking: 'Проверка...', checkAll: 'Проверить все', statusValid: 'Работает', statusInvalid: 'Не работает', statusUnknown: 'Не проверен', lastChecked: 'Проверено', editKey: 'Изменить', saveKey: 'Сохранить', bulkImport: 'Массовый импорт', bulkImportTitle: 'Массовый импорт ключей', bulkImportHelp: 'По одному ключу в строке. Формат: Название, ключ, ID модели (опционально). Base URL для всех строк задаётся ниже.', bulkBaseUrlHelp: 'применяется ко всем строкам, в которых не указан свой URL', bulkImportPlaceholder: 'Codex Sale, sk-clb-..., gpt-5.4-mini\nOpenAI, sk-..., gpt-4o-mini\nGroq, gsk-..., llama-3.3-70b-versatile, https://api.groq.com/openai/v1', importKeys: 'Импортировать', importing: 'Импорт...', importDone: 'Импортировано: {created}, ошибок: {failed}', bulkModelsLabel: 'ID моделей', bulkModelsHelp: 'через запятую; каждый ключ проверяется по этим моделям, назначается первая рабочая', bulkKeysLabel: 'API-ключи', bulkKeysHelp: 'по одному ключу в строке', bulkProbing: 'Проверка моделей…', bulkNoWorkingModel: 'нет рабочей модели ({n})',
    newGroup: 'Новая группа', groupNamePlaceholder: 'Название группы', createGroup: 'Создать группу', deleteGroup: 'Удалить группу', renameGroup: 'Переименовать группу', noGroup: 'Без группы', keyGroupLabel: 'Группа', groupEmpty: 'В этой группе пока нет ключей', keysCount: '{n} ключ(ей)', diagnoseKey: 'Диагностика ключа',
    generating: 'Генерирует ответ…', writingFile: 'Пишет код:', doneIn: 'Готово за {t}', durSec: '{s} с', durMin: '{m} мин {s} с', filesChanged: 'файлов: {n}', linesWritten: 'строк: {n}',
    pluginsTitle: 'Плагины', allPlugins: 'Все плагины', installed: 'Установленные', install: 'Установить', uninstall: 'Удалить', pluginUtility: 'Утилита', pluginSkill: 'Навык ИИ', pluginSystemMod: 'Системный мод', pluginScope: 'Область', pluginDocs: 'Документация', pluginChangelog: 'Обновления', pluginRecommendations: 'Рекомендации', whereItAppears: 'Где появится после установки',
    modeHtml: 'HTML', modeIde: 'IDE', ideModeHint: 'IDE-режим: Aura создаёт React-компоненты с файловым деревом и live-превью.', ideModeEmpty: 'Попросите Aura создать React-компонент — файлы и превью появятся здесь.',
    generalDescription: 'Настройте поведение IDE и параметры редактора.', generalChatSection: 'Чат', generalEditorSection: 'Редактор', defaultMode: 'Режим по умолчанию', defaultModeHelp: 'Режим, который будет использоваться при создании нового чата.', editorFontSize: 'Размер шрифта', editorFontSizeHelp: 'Размер шрифта в редакторе кода (Monaco).', editorTabSize: 'Размер таба', editorTabSizeHelp: 'Количество пробелов при нажатии Tab в редакторе.', editorWordWrap: 'Перенос строк', editorWordWrapHelp: 'Автоматически переносить длинные строки в редакторе.', autoPreview: 'Автообновление превью', autoPreviewHelp: 'Обновлять превью автоматически после каждого ответа Aura.',
    memoriesDescription: 'Управляйте тем, что Aura помнит о вас и вашем стиле работы.', memoriesSettingsSection: 'Настройки памяти', memoriesListSection: 'Воспоминания', memoriesActive: 'активных', memoriesEnabled: 'Использовать память', memoriesEnabledHelp: 'Добавлять активные воспоминания в системный промпт каждого чата.', memoriesAutoExtract: 'Автоизвлечение', memoriesAutoExtractHelp: 'После каждого чата Aura предлагает новые воспоминания на основе переписки.', memoriesMaxCount: 'Максимум воспоминаний', memoriesMaxCountHelp: 'Сколько активных воспоминаний передаётся в контекст.',
    memoryAdd: 'Добавить', memoryEdit: 'Редактировать', memoryDelete: 'Удалить', memoryExport: 'Экспорт', memoryClearAll: 'Очистить всё', memoryClearAllConfirmTitle: 'Удалить все воспоминания?', memoryClearAllConfirmDesc: 'Это действие необратимо. Все воспоминания будут удалены.', memoriesEmpty: 'Нет воспоминаний', memoriesEmptyHelp: 'Добавьте первое воспоминание вручную или включите автоизвлечение из чатов.', memoryToggle: 'Включить/выключить воспоминание', memoryType: 'Тип', memoryContent: 'Содержание', memoryContentPlaceholder: 'Например: предпочитаю использовать Tailwind CSS вместо styled-components...', memorySourceAuto: '(авто)', memoryTypeFact: 'Факт', memoryTypeCodingStyle: 'Стиль кода', memoryTypeProjectContext: 'Контекст проекта', memoryTypePreference: 'Предпочтение',
    figmaFrameUrl: 'URL фрейма Figma', figmaToken: 'Персональный токен Figma', figmaTokenHelp: 'Создайте Personal Access Token в настройках Figma → Account → Personal access tokens.', figmaExtract: 'Извлечь дизайн', figmaUrlRequired: 'Укажите ссылку на фрейм Figma', figmaTokenRequired: 'Укажите персональный токен Figma', figmaInvalidUrl: 'Не удалось найти fileKey в ссылке. Убедитесь, что это ссылка figma.com/file/...', figmaFetchError: 'Не удалось получить данные из Figma. Проверьте токен и ссылку.', figmaPremiumTitle: 'Функция доступна в Pro', figmaPremiumDesc: 'Импорт из Figma доступен в тарифе Pro. Обновите план, чтобы использовать эту функцию.', figmaUpgradeToPro: 'Перейти на Pro',
    mcpNoServers: 'Нет добавленных серверов MCP. Нажмите «Добавить сервер» чтобы начать.', mcpServerName: 'Название сервера', mcpAuthType: 'Тип авторизации', mcpAuthNone: 'Без авторизации', mcpAuthBearer: 'Bearer токен', mcpAuthOAuth: 'OAuth 2.0', mcpToken: 'Токен', deleteMcp: 'Удалить сервер MCP',
    ideConsole: 'Консоль', ideConsoleEmpty: 'Логи и ошибки превью появятся здесь. Введите JS-выражение ниже, чтобы выполнить его в превью.', ideConsoleClear: 'Очистить консоль', ideConsoleEval: 'Выполнить JS в превью…', ideFiles: 'Файлы', ideNewFile: 'Новый файл', ideNewFolder: 'Новая папка', ideRename: 'Переименовать', ideDelete: 'Удалить', ideDeleteFolderConfirm: 'Удалить папку со всем содержимым?', ideFileExists: 'Такой путь уже существует', idePreviewTab: 'Превью', ideCodeTab: 'Код', ideSplitTab: 'Сплит', ideOpenNewTab: 'Открыть в новой вкладке', searchChatsPlaceholder: 'Поиск по чатам…', searchNoResults: 'Ничего не найдено', regenerate: 'Перегенерировать', retry: 'Повторить', rateLimited: 'Дневной лимит встроенных моделей исчерпан. Собственные API-ключи не ограничиваются.', rateLimitedCta: 'Добавить свой ключ', mobileChatTab: 'Чат', mobilePreviewTab: 'Превью', ideSaving: 'Сохранение…', ideSaved: 'Сохранено ✓', ideDesignTab: 'Дизайн', ideLogsTab: 'Логи', ideTerminalTab: 'Терминал', ideLogsFilter: 'Фильтр…', ideLogsEmpty: 'Логи превью появятся здесь.', ideFileSearch: 'Поиск файлов…', ideCollapseAll: 'Свернуть всё', ideOpenFile: 'Открыть', ideDuplicate: 'Дублировать', ideCopyPath: 'Копировать путь', ideDownloadFile: 'Скачать', ideDesignHint: 'Кликните элемент в превью — он попадёт в контекст следующего сообщения', selectedElement: 'Выбранный элемент', viewerModeNotice: 'Режим просмотра — у вас доступ только на чтение этого проекта.',
    publishTitle: 'Публикация проекта', publishSubtitle: 'Проект упаковывается в полноценное Vite + React приложение.', publishGithubTab: 'GitHub', publishSshTab: 'Свой сервер (SSH)', publishAuraTab: 'Aura Хостинг', ghToken: 'GitHub токен', ghTokenHelp: 'Personal Access Token со scope «repo». Хранится только в вашем браузере.', ghRepoName: 'Название репозитория', ghPrivate: 'Приватный репозиторий', ghPublish: 'Опубликовать на GitHub', ghPublishing: 'Публикация…', ghSuccess: 'Репозиторий опубликован!', ghOpenRepo: 'Открыть репозиторий', ghTokenSavedPlaceholder: 'Используется сохранённый токен', ghTokenSavedHint: 'Токен подключён в Настройки → Интеграции. Поле можно оставить пустым или указать другой токен.', sshHost: 'Хост (IP или домен)', sshUser: 'Пользователь', sshPort: 'Порт', sshPath: 'Путь на сервере', sshDownload: 'Скачать пакет деплоя (ZIP)', sshHelp: 'Браузер не может открыть SSH-соединение напрямую, поэтому Aura собирает готовый пакет: проект + Dockerfile + deploy.sh с вашими параметрами. Распакуйте и запустите одну команду:', auraHelp: 'Деплой на инфраструктуру Aura требует отдельный Docker-образ на проект и VPS с Docker. Скачайте Docker-бандл — в нём Dockerfile, docker-compose.yml и nginx.conf, готовые к запуску на любом VPS:', auraDownload: 'Скачать Docker-бандл (ZIP)', auraRequirements: 'Требования: VPS (1 vCPU / 1 ГБ), Docker 24+, docker compose v2.', downloadZip: 'Скачать ZIP проекта', copied: 'Скопировано', copy: 'Копировать',
  },
  en: {
    homeTitle: 'What do you want to create?',
    home: 'Home', projects: 'Projects', chats: 'Chats', team: 'Team', plugins: 'Plugins & Skills', myApi: 'My API', freebies: 'Freebies', search: 'Search', newChat: 'New Chat', newChatOptions: 'New chat options', favorites: 'Favorites', recentChats: 'Recent Chats', free: 'Free',
    profile: 'Profile', settings: 'Account Settings', signOut: 'Sign Out', signingOut: 'Signing out...', guest: 'Guest', switchAccount: 'Switch account', noOtherAccounts: 'No other accounts', addAccount: 'Add account', continueAsGuest: 'Continue as guest', language: 'Language', languageHelp: 'Aura interface language.',
    promptPlaceholder: 'Ask Aura to build...', promptLabel: 'Prompt', addContent: 'Add content', importGithub: 'Import from GitHub', createFigma: 'Create from Figma', premium: 'Premium', uploadComputer: 'Upload from computer', generateImages: 'Generate Images', toggleImages: 'Toggle image generation', skills: 'Plugins & Skills', webSearch: 'Web Search', codeInterpreter: 'Code Interpreter', diagrams: 'Diagrams', folder: 'Folder', newFolder: 'New folder', attachExisting: 'Attach existing', instructions: 'Instructions', editInstructions: 'Edit instructions', resetDefault: 'Reset to default', mcps: 'MCPs', manageMcps: 'Manage MCPs', addServer: 'Add server', autoPermissions: 'Auto Permissions', askEveryTime: 'Ask every time', allowAll: 'Allow all', project: 'Project', voiceInput: 'Voice input', selectModel: 'Select model', addApiKey: 'Add API key', myApiDescription: 'Add keys from external providers — they will appear in the model list.', newKey: 'New key', createKey: 'Create key', noKeysTitle: 'No keys yet', noKeysHelp: 'Add your first API key to use your own models in Aura.', keyNameLabel: 'Name', keyNamePlaceholder: 'e.g. OpenAI GPT-4o', keyValueLabel: 'API key', keyValuePlaceholder: 'sk-...', deleteKey: 'Delete key', addedOn: 'Added', searchProjects: 'Search projects...', noProjectsFound: 'No projects found', newProject: 'New Project', draft: 'Draft', createProjectPlaceholder: 'Project name', create: 'Create', cancel: 'Cancel',
    profileTitle: 'Profile', profileDescription: 'Manage how you appear in Aura.', backHome: 'Back to home', avatar: 'Avatar', avatarHelp: 'Click the picture to upload. JPG, PNG or WebP.', changeAvatar: 'Change avatar', yourAvatar: 'Your avatar', chooseImage: 'Please choose an image file', processImageError: 'Could not process this image', canvasError: 'Canvas not supported', imageLoadError: 'Could not load image', name: 'Name', nameHelp: 'Your display name. You can change it anytime — your tag stays the same.', save: 'Save', saved: 'Saved', uniqueTag: 'Unique tag', tagPermanent: 'Your tag has been changed and is now permanent.', tagFromLogin: 'Created from your login.', lettersOnly: 'Letters, numbers, underscores, dots and dashes only', change: 'Change', tagWarning: 'The tag can be changed only once. Choose carefully.', about: 'About', bioHelp: 'A short description about you. Up to 500 characters.', bioPlaceholder: 'Tell something about yourself...',
    preferences: 'Preferences', preferencesDescription: 'Manage your account settings and workspace preferences.', account: 'Account', workspace: 'Workspace', general: 'General', memories: 'Memories', integrations: 'Integrations', billing: 'Billing', members: 'Members', usage: 'Usage & Activity', apiKeys: 'API Keys', skillsNav: 'Skills', pluginsNav: 'Plugins', suggestions: 'Suggestions', suggestionsHelp: 'Get relevant in-chat suggestions to refine your project.', soundNotifications: 'Sound Notifications', soundHelp: 'A sound will play when Aura is finished responding and the window is not focused.', chatPosition: 'Chat Position', chatPositionHelp: 'Choose which side of the screen the chat is on.', left: 'Left', right: 'Right', customInstructions: 'Custom Instructions', customInstructionsHelp: 'Manage your custom user rules or preferences for the LLM.', instructionsPlaceholder: 'These instructions get sent to Aura in all chats across all projects.', interfaceTheme: 'Interface and Theme', theme: 'Theme', themeHelp: 'Choose how Aura looks on your device.', systemTheme: 'System theme', lightTheme: 'Light theme', darkTheme: 'Dark theme',
    createAccount: 'Create your account', welcomeBack: 'Welcome back', signupSubtitle: 'Sign up to start building with Aura', signinSubtitle: 'Sign in to continue to Aura', username: 'Username', emailOrUsername: 'Email or username', password: 'Password', showPassword: 'Show password', hidePassword: 'Hide password', accountCreated: 'Account created', signedIn: 'Signed in', signUp: 'Sign up', signIn: 'Sign in', or: 'or', haveAccount: 'Already have an account?', noAccount: "Don't have an account?", genericError: 'Something went wrong', namePlaceholder: 'Your name', identifierPlaceholder: 'you@example.com or your_login',
    forgotPassword: 'Forgot password?', forgotTitle: 'Reset your password', forgotSubtitle: 'Enter your email and we will send you a reset link.', sendResetLink: 'Send reset link', resetLinkSent: 'If this email is registered, a reset link has been sent.', backToSignIn: 'Back to sign in', resetTitle: 'New password', resetSubtitle: 'Choose a new password for your account.', newPassword: 'New password', updatePassword: 'Update password', passwordUpdated: 'Password updated', invalidResetToken: 'This link is invalid or expired. Please request a new one.', verificationNote: 'We sent you an email to verify your address.', securityTitle: 'Security', emailVerified: 'Email verified', emailNotVerified: 'Email not verified — check your inbox or resend the email.', resendVerification: 'Resend email', verificationSent: 'Sent', changePassword: 'Change password', currentPassword: 'Current password', dangerZone: 'Danger zone', deleteAccount: 'Delete account', deleteAccountHelp: 'Your account and all data (chats, projects, files, keys, memories) will be permanently deleted.', deleteAccountConfirm: 'Yes, delete forever',
    send: 'Send', stop: 'Stop', thinking: 'Aura is thinking...', chatError: 'Failed to get a response. Please try again.', publish: 'Publish', previewGenerating: 'Aura is generating a preview...', previewEmpty: 'Ask Aura to build a site or UI — the preview will appear here.', previewUpdated: 'Preview updated', renameChatLabel: 'Rename', deleteChatLabel: 'Delete', noRecentChats: 'No chats yet', openMenu: 'Open menu', closeMenu: 'Close menu', chatOptions: 'Chat options',
    blankChat: 'Blank Chat', blankProject: 'Blank Project', createBlankProject: 'Create Blank Project', blankProjectHelp: 'This will create a blank project you can start coding in.', projectNameLabel: 'Project Name', back: 'Back', createProjectAction: 'Create Project', importFromUrl: 'Import from a URL', importAction: 'Import', selectRepository: 'Select a Repository', connectGithub: 'Connect GitHub', githubComingSoon: 'GitHub connection is coming soon', invalidRepoUrl: 'Enter a valid GitHub repository URL', jumpBackIn: 'Jump back in', renameProject: 'Rename Project', copyProjectId: 'Copy Project ID', viewAllChats: 'View All Chats', deleteProject: 'Delete Project', projectOptions: 'Project options', projectIdCopied: 'ID copied', addToFavorites: 'Add to favorites', removeFromFavorites: 'Remove from favorites', noFavorites: 'No favorite chats yet', daysAgo: '{n}d ago', hoursAgo: '{n}h ago', justNow: 'just now',
    keyModelLabel: 'Model ID', keyModelPlaceholder: 'e.g. gpt-4o-mini', keyBaseUrlLabel: 'Base URL', keyBaseUrlPlaceholder: 'https://api.openai.com/v1', advancedOptional: 'Advanced (optional)', checkKey: 'Check', checking: 'Checking...', checkAll: 'Check all', statusValid: 'Working', statusInvalid: 'Not working', statusUnknown: 'Not checked', lastChecked: 'Checked', editKey: 'Edit', saveKey: 'Save', bulkImport: 'Bulk import', bulkImportTitle: 'Bulk import keys', bulkImportHelp: 'One key per line. Format: Name, key, model ID (optional). Set a default Base URL below to apply to all lines that have no URL.', bulkBaseUrlHelp: 'applied to all lines that do not specify their own URL', bulkImportPlaceholder: 'Codex Sale, sk-clb-..., gpt-5.4-mini\nOpenAI, sk-..., gpt-4o-mini\nGroq, gsk-..., llama-3.3-70b-versatile, https://api.groq.com/openai/v1', importKeys: 'Import', importing: 'Importing...', importDone: 'Imported: {created}, failed: {failed}', bulkModelsLabel: 'Model IDs', bulkModelsHelp: 'comma-separated; each key is probed against these, first working one is assigned', bulkKeysLabel: 'API keys', bulkKeysHelp: 'one key per line', bulkProbing: 'Probing models…', bulkNoWorkingModel: 'no working model ({n})',
    newGroup: 'New group', groupNamePlaceholder: 'Group name', createGroup: 'Create group', deleteGroup: 'Delete group', renameGroup: 'Rename group', noGroup: 'No group', keyGroupLabel: 'Group', groupEmpty: 'No keys in this group yet', keysCount: '{n} key(s)', diagnoseKey: 'Key diagnostics',
    generating: 'Generating…', writingFile: 'Writing', doneIn: 'Done in {t}', durSec: '{s}s', durMin: '{m}m {s}s', filesChanged: '{n} files', linesWritten: '{n} lines',
    pluginsTitle: 'Plugins', allPlugins: 'All plugins', installed: 'Installed', install: 'Install', uninstall: 'Uninstall', pluginUtility: 'Utility', pluginSkill: 'AI Skill', pluginSystemMod: 'System Mod', pluginScope: 'Scope', pluginDocs: 'Documentation', pluginChangelog: 'Changelog', pluginRecommendations: 'Recommendations', whereItAppears: 'Where it appears after install',
    modeHtml: 'HTML', modeIde: 'IDE', ideModeHint: 'IDE mode: Aura generates React components with a file tree and live preview.', ideModeEmpty: 'Ask Aura to build a React component — files and preview will appear here.',
    generalDescription: 'Configure IDE behavior and editor preferences.', generalChatSection: 'Chat', generalEditorSection: 'Editor', defaultMode: 'Default Mode', defaultModeHelp: 'The mode that will be used when creating a new chat.', editorFontSize: 'Font Size', editorFontSizeHelp: 'Font size in the code editor (Monaco).', editorTabSize: 'Tab Size', editorTabSizeHelp: 'Number of spaces inserted when pressing Tab in the editor.', editorWordWrap: 'Word Wrap', editorWordWrapHelp: 'Automatically wrap long lines in the editor.', autoPreview: 'Auto Preview', autoPreviewHelp: 'Automatically refresh the preview after each Aura response.',
    memoriesDescription: 'Manage what Aura remembers about you and your coding style.', memoriesSettingsSection: 'Memory Settings', memoriesListSection: 'Memories', memoriesActive: 'active', memoriesEnabled: 'Use Memories', memoriesEnabledHelp: 'Inject active memories into the system prompt of every chat.', memoriesAutoExtract: 'Auto-extract', memoriesAutoExtractHelp: 'After each chat, Aura suggests new memories based on the conversation.', memoriesMaxCount: 'Max Memories', memoriesMaxCountHelp: 'How many active memories are passed into context.',
    memoryAdd: 'Add', memoryEdit: 'Edit', memoryDelete: 'Delete', memoryExport: 'Export', memoryClearAll: 'Clear all', memoryClearAllConfirmTitle: 'Delete all memories?', memoryClearAllConfirmDesc: 'This action is irreversible. All memories will be permanently deleted.', memoriesEmpty: 'No memories yet', memoriesEmptyHelp: 'Add your first memory manually or enable auto-extraction from chats.', memoryToggle: 'Toggle memory', memoryType: 'Type', memoryContent: 'Content', memoryContentPlaceholder: 'e.g. I prefer using Tailwind CSS over styled-components...', memorySourceAuto: '(auto)', memoryTypeFact: 'Fact', memoryTypeCodingStyle: 'Coding Style', memoryTypeProjectContext: 'Project Context', memoryTypePreference: 'Preference',
    figmaFrameUrl: 'Figma frame URL', figmaToken: 'Figma Personal Token', figmaTokenHelp: 'Create a Personal Access Token in Figma Settings → Account → Personal access tokens.', figmaExtract: 'Extract design', figmaUrlRequired: 'Please enter a Figma frame URL', figmaTokenRequired: 'Please enter your Figma personal token', figmaInvalidUrl: 'Could not find fileKey in URL. Make sure it is a figma.com/file/... link.', figmaFetchError: 'Failed to fetch data from Figma. Check your token and URL.', figmaPremiumTitle: 'Pro feature', figmaPremiumDesc: 'Figma import is available on the Pro plan. Upgrade to use this feature.', figmaUpgradeToPro: 'Upgrade to Pro',
    mcpNoServers: 'No MCP servers added yet. Click "Add server" to get started.', mcpServerName: 'Server name', mcpAuthType: 'Auth type', mcpAuthNone: 'No auth', mcpAuthBearer: 'Bearer token', mcpAuthOAuth: 'OAuth 2.0', mcpToken: 'Token', deleteMcp: 'Delete MCP server',
    ideConsole: 'Console', ideConsoleEmpty: 'Preview logs and errors will appear here. Type a JS expression below to run it inside the preview.', ideConsoleClear: 'Clear console', ideConsoleEval: 'Run JS in the preview…', ideFiles: 'Files', ideNewFile: 'New file', ideNewFolder: 'New folder', ideRename: 'Rename', ideDelete: 'Delete', ideDeleteFolderConfirm: 'Delete this folder and everything inside?', ideFileExists: 'This path already exists', idePreviewTab: 'Preview', ideCodeTab: 'Code', ideSplitTab: 'Split', ideOpenNewTab: 'Open in new tab', searchChatsPlaceholder: 'Search chats…', searchNoResults: 'No results', regenerate: 'Regenerate', retry: 'Retry', rateLimited: 'Daily limit for built-in models reached. Your own API keys are never limited.', rateLimitedCta: 'Add your key', mobileChatTab: 'Chat', mobilePreviewTab: 'Preview', ideSaving: 'Saving…', ideSaved: 'Saved ✓', ideDesignTab: 'Design', ideLogsTab: 'Logs', ideTerminalTab: 'Terminal', ideLogsFilter: 'Filter…', ideLogsEmpty: 'Preview logs will appear here.', ideFileSearch: 'Search files…', ideCollapseAll: 'Collapse all', ideOpenFile: 'Open', ideDuplicate: 'Duplicate', ideCopyPath: 'Copy path', ideDownloadFile: 'Download', ideDesignHint: 'Click an element in the preview — it will be attached to your next message', selectedElement: 'Selected element', viewerModeNotice: 'View mode — you have read-only access to this project.',
    publishTitle: 'Publish project', publishSubtitle: 'The project is packaged as a complete Vite + React app.', publishGithubTab: 'GitHub', publishSshTab: 'Your server (SSH)', publishAuraTab: 'Aura Hosting', ghToken: 'GitHub token', ghTokenHelp: 'Personal Access Token with the "repo" scope. Stored only in your browser.', ghRepoName: 'Repository name', ghPrivate: 'Private repository', ghPublish: 'Publish to GitHub', ghPublishing: 'Publishing…', ghSuccess: 'Repository published!', ghOpenRepo: 'Open repository', ghTokenSavedPlaceholder: 'Using the saved token', ghTokenSavedHint: 'A token is connected in Settings → Integrations. Leave empty or provide another one.', sshHost: 'Host (IP or domain)', sshUser: 'User', sshPort: 'Port', sshPath: 'Path on server', sshDownload: 'Download deploy bundle (ZIP)', sshHelp: 'A browser cannot open a raw SSH connection, so Aura builds a ready-made bundle: project + Dockerfile + deploy.sh preconfigured with your settings. Unpack and run a single command:', auraHelp: 'Deploying to Aura infrastructure requires a dedicated Docker image per project and a VPS with Docker. Download the Docker bundle — it contains a Dockerfile, docker-compose.yml and nginx.conf ready to run on any VPS:', auraDownload: 'Download Docker bundle (ZIP)', auraRequirements: 'Requirements: VPS (1 vCPU / 1 GB), Docker 24+, docker compose v2.', downloadZip: 'Download project ZIP', copied: 'Copied', copy: 'Copy',
  },
} as const

const LanguageContext = createContext<LanguageContextValue | null>(null)

function getCookieLanguage(): LanguageCode {
  if (typeof document === 'undefined') return 'ru'
  const value = document.cookie
    .split('; ')
    .find((row) => row.startsWith(`${COOKIE_KEY}=`))
    ?.split('=')[1]
  return value === 'en' ? 'en' : 'ru'
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => getCookieLanguage())

  const setLanguage = (code: LanguageCode) => {
    setLanguageState(code)
    document.documentElement.lang = code
    document.cookie = `${COOKIE_KEY}=${code}; path=/; max-age=31536000; samesite=lax`
  }

  const t = (key: TranslationKey) => translations[language][key]

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within a LanguageProvider')
  return ctx
}
