//! Aura IDE — Tauri backend.
//!
//! Обёртка над `aura-core`: превращает наши команды в `#[tauri::command]`,
//! навешивает специфические для рантайма вещи (окна, события, keychain, PTY).

pub mod commands;
pub mod pty;
pub mod state;
pub mod watcher;

use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

/// Точка входа, вызывается из `src-tauri/src/main.rs`.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info,aura_core=debug,aura_ide_lib=debug".into()),
        )
        .init();

    let specta_builder = build_specta();

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .manage(state::AppState::new())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);
            // Для non-mobile — свою титульную полосу, окно уже без декораций.
            #[cfg(desktop)]
            {
                if let Some(w) = app.get_webview_window("main") {
                    let _ = w.set_shadow(true);
                }
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("failed to run Aura IDE");
}

/// Сборка specta-биндингов. В dev-сборке дополнительно экспортируем TS-файл,
/// который потребляет Агент 2.
fn build_specta() -> Builder {
    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::fs::fs_read_dir,
        commands::fs::fs_read_file,
        commands::fs::fs_write_file,
        commands::fs::fs_create_file,
        commands::fs::fs_create_dir,
        commands::fs::fs_rename,
        commands::fs::fs_delete,
        commands::fs::fs_watch,
        commands::fs::fs_unwatch,
        commands::git::git_status,
        commands::git::git_branches,
        commands::git::git_checkout,
        commands::git::git_stage,
        commands::git::git_unstage,
        commands::git::git_commit,
        commands::git::git_diff_file,
        commands::git::git_pull,
        commands::git::git_push,
        commands::settings::settings_load,
        commands::settings::settings_save,
        commands::settings::recents_list,
        commands::settings::recents_touch,
        commands::settings::recents_remove,
        commands::search::search_in_project,
        commands::pty::pty_create,
        commands::pty::pty_write,
        commands::pty::pty_resize,
        commands::pty::pty_kill,
        commands::window::window_minimize,
        commands::window::window_toggle_maximize,
        commands::window::window_close,
    ]);

    #[cfg(debug_assertions)]
    {
        use specta_typescript::Typescript;
        let ts = Typescript::default()
            .header("// Auto-generated by tauri-specta — do not edit.\n");
        if let Err(e) = builder.export(ts, "../src/lib/tauriApi.ts") {
            tracing::warn!("specta export failed: {e}");
        }
    }

    builder
}
